Algoritmo "idades"

Var

 nome1: caractere
 nome2: caractere
 idade1: inteiro
 idade2:inteiro
 mediaidade: real

Inicio
   escreval("Digite seu nome: ")
   leia(nome1)
   escreval("Digite sua idade: ")
   leia(idade1)
   
   escreval("Digite seu nome: ")
   leia(nome2)
   escreval("Digite sua idade: ")
   leia(idade2)
   
   mediaidade <- (idade1 + idade2) / 2
   
   escreval("A idade media de ", nome1, " e ", nome2, " é de ", mediaidade)

Fimalgoritmo